### PR TITLE
test: fix more flaky network tests

### LINKED ISSUE #168: The build failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 8290caf537157ece467da864d15333e0f1c7a1e6
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/5695a727-1f7d-4e25-a037-782faeff38a1), [Sponge](http://sponge2/5695a727-1f7d-4e25-a037-782faeff38a1)
status: failed
<details><summary>Test output</summary><br><pre>java.lang.AssertionError: Operation failed: Error{errors=[Errors{code=RESOURCE_IN_USE_BY_ANOTHER_RESOURCE, location=null, message=The network resource 'projects/gcloud-devel/global/networks/test-network-ce0251d8' is already being used by 'projects/gcloud-devel/global/firewalls/test-network-ce0251d8-7jwjwgrefj3dgqccoz4jhi4s-1'}]}
	at org.junit.Assert.fail(Assert.java:89)
	at com.google.cloud.compute.v1.it.BaseTest.waitForOperation(BaseTest.java:108)
	at com.google.cloud.compute.v1.it.ITNetworkTest.tearDown(ITNetworkTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
</pre></details>

### PR DESCRIPTION
**Pull request by chingor13**
Turns out we're racing against internal rules that are creating firewall rules for network interfaces. This PR uses a helper to clean up network interfaces by first deleting all firewalls associated with that network, then deleting the network.

Fixes #168

### CODE REVIEW

File: src/test/java/com/google/cloud/compute/v1/it/BaseTest.java [hunk 1]
```diff
@@ -120,11 +120,30 @@ protected static Operation waitForOperation(Operation operation) {
...
     FirewallSettings firewallSettings =
         FirewallSettings.newBuilder().setCredentialsProvider(credentialsProvider).build();
     FirewallClient firewallClient = FirewallClient.create(firewallSettings);
 
+    // TODO: switch to firewall list filter
+    List<Firewall> firewalls =
+        Lists.newArrayList(firewallClient.listFirewalls(PROJECT_NAME).iterateAll());
+    for (Firewall firewall : firewalls) {
+      if (firewall.getNetwork().equals(network.getSelfLink())) {
+        System.out.println("deleting firewall: " + firewall.getSelfLink());
```
Comment (kolea2) [inline src/test/java/com/google/cloud/compute/v1/it/BaseTest.java:133]: remove this?

File: src/test/java/com/google/cloud/compute/v1/it/BaseTest.java [hunk 2]
```diff
@@ -120,11 +120,30 @@ protected static Operation waitForOperation(Operation operation) {
...
+        waitForOperation(firewallClient.deleteFirewall(firewall.getSelfLink()));
+      }
+    }
+
+    NetworkSettings networkSettings =
+        NetworkSettings.newBuilder().setCredentialsProvider(credentialsProvider).build();
+    NetworkClient networkClient = NetworkClient.create(networkSettings);
+
+    System.out.println("deleting network:" + network.getSelfLink());
```
Comment (kolea2) [inline src/test/java/com/google/cloud/compute/v1/it/BaseTest.java:142]: same here, may want to delete or switch to logging

File: src/test/java/com/google/cloud/compute/v1/it/BaseTest.java [hunk 3]
```diff
@@ -120,11 +120,28 @@ protected static Operation waitForOperation(Operation operation) {
...
+    // TODO: switch to firewall list filter
+    List<Firewall> firewalls =
+        Lists.newArrayList(firewallClient.listFirewalls(PROJECT_NAME).iterateAll());
+    for (Firewall firewall : firewalls) {
+      if (firewall.getNetwork().equals(network.getSelfLink())) {
+        waitForOperation(firewallClient.deleteFirewall(firewall.getSelfLink()));
+      }
+    }
+
+    NetworkSettings networkSettings =
```
Comment (kolea2) [inline src/test/java/com/google/cloud/compute/v1/it/BaseTest.java:137]: how come this logic moved from setUp to cleanup?

**Review by kolea2 — COMMENTED** [review]
looks fine pending one question

File: src/test/java/com/google/cloud/compute/v1/it/BaseTest.java (hunk 3 above)
Comment (chingor13) [reply src/test/java/com/google/cloud/compute/v1/it/BaseTest.java:137]: In `ITNetworkTest`, the network client is created at setup time and is reused throughout the test. In the `ITFirewallTest` it was used to create a separate test network for use by the firewalls.

We could re-use the same `NetworkClient` from the test and pass both it and the `FirewallClient` to the helper functions, but it's doesn't seem like too big of a deal.

**Review by kolea2 — APPROVED** [review]
